# Generated by Django 3.2.9 on 2021-11-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.CharField(default='https://www.youtube.com/', max_length=255),
            preserve_default=False,
        ),
    ]
